version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    #ignore:
    #  - dependency-name: "org.jetbrains.kotlin:kotlin-stdlib" # Kotlin の更新を無視したい場合
    labels:
      - "dependencies"
    assignees:
      - "emergent"
